name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Unit test
        shell: bash
        run: |
            python3 -m unittest -v tree.py
