name: Run Unit Tests

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unit test
        shell: bash
        run: |
            python3 -m unittest -v tree.py
